name: Update package-lock.json

on:
  workflow_dispatch: # permet de lancer manuellement
  push:
    branches:
      - main   # se déclenche à chaque push sur main

jobs:
  update-lockfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
